In [ ]:
from google.colab import drive
drive.mount('/content/drive')
import os
criminals_path = '/content/drive/MyDrive/criminals/rajasthanmetadata/'

# Check if it exists
if os.path.exists(criminals_path):
    print("✓ Found criminals folder!")
    files = os.listdir(criminals_path)
    print(f"  Contains {len(files)} files")
else:
    print("✗ Folder not found. Creating it...")
    os.makedirs(criminals_path)

Mounted at /content/drive
✓ Found criminals folder!
  Contains 5000 files


In [ ]:
!pip install transformers

In [ ]:
from PIL import Image
import torch
from transformers import CLIPProcessor, CLIPModel
model = CLIPModel.from_pretrained("openai/clip-vit-base-patch16")
processor = CLIPProcessor.from_pretrained("openai/clip-vit-base-patch16")


/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


config.json: 0.00B [00:00, ?B/s]

pytorch_model.bin:   0%|          | 0.00/599M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/398 [00:00<?, ?it/s]

CLIPModel LOAD REPORT from: openai/clip-vit-base-patch16
Key                                  | Status     |  | 
-------------------------------------+------------+--+-
vision_model.embeddings.position_ids | UNEXPECTED |  | 
text_model.embeddings.position_ids   | UNEXPECTED |  | 

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.


model.safetensors:   0%|          | 0.00/599M [00:00<?, ?B/s]

preprocessor_config.json:   0%|          | 0.00/316 [00:00<?, ?B/s]

The image processor of type `CLIPImageProcessor` is now loaded as a fast processor by default, even if the model checkpoint was saved with a slow processor. This is a breaking change and may produce slightly different outputs. To continue using the slow processor, instantiate this class with `use_fast=False`. 


tokenizer_config.json:   0%|          | 0.00/905 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/389 [00:00<?, ?B/s]

In [ ]:
text_prompts = [
    "a man with a beard",
    "a man with no beard",
    "a man with a moustache",
    "a man without a moustache",
    "a person with a round face",
    "a person with a slim face",
    "a messy looking person",
    "a well groomed person"
]

face_dictionary = {
    "a man with a beard":[],
    "a man with no beard":[],
    "a man with a moustache":[],
    "a man without a moustache":[],
    "a person with a round face":[],
    "a person with a slim face":[],
    "a messy looking person":[],
    "a well groomed person":[]
}

In [ ]:
for i in range(0,5000):
    test_img_path = f"/content/drive/MyDrive/criminals/rajasthanmetadata/{i:05}.jpg"
    image = Image.open(test_img_path)
    image = image.convert("RGB")
    print(f"{i:05}.jpg is done")
    inputs = processor(
       text=text_prompts, images=image, return_tensors="pt", padding=True
     )
    with torch.inference_mode():
      outputs = model(**inputs)
    logits_per_image = outputs.logits_per_image  # this is the image-text similarity score
    probs = logits_per_image.softmax(dim=1)
    print(probs)
    if probs[0][0] > probs[0][1]:
      face_dictionary["a man with a beard"].append(f"{i:05}.jpg")
    else:
      face_dictionary["a man with no beard"].append(f"{i:05}.jpg")
    if probs[0][2] > probs[0][3]:
      face_dictionary["a man with a moustache"].append(f"{i:05}.jpg")
    else:
      face_dictionary["a man without a moustache"].append(f"{i:05}.jpg")
    if probs[0][4] > probs[0][5]:
      face_dictionary["a person with a round face"].append(f"{i:05}.jpg")
    else:
      face_dictionary["a person with a slim face"].append(f"{i:05}.jpg")
    if probs[0][6] > probs[0][7]:
      face_dictionary["a messy looking person"].append(f"{i:05}.jpg")
    else:
      face_dictionary["a well groomed person"].append(f"{i:05}.jpg")

Streaming output truncated to the last 5000 lines.
tensor([[0.0291, 0.1522, 0.0694, 0.1079, 0.2235, 0.3664, 0.0052, 0.0461]])
02615.jpg is done
tensor([[0.0097, 0.0841, 0.0145, 0.0282, 0.4544, 0.2986, 0.0038, 0.1067]])
02616.jpg is done
tensor([[0.0125, 0.0579, 0.1491, 0.0989, 0.0324, 0.4844, 0.0016, 0.1632]])
02617.jpg is done
tensor([[0.0287, 0.0448, 0.1144, 0.1775, 0.0443, 0.4011, 0.0025, 0.1868]])
02618.jpg is done
tensor([[0.0059, 0.3555, 0.0173, 0.1342, 0.0771, 0.2769, 0.0052, 0.1280]])
02619.jpg is done
tensor([[0.0075, 0.0869, 0.0885, 0.1313, 0.0846, 0.5285, 0.0034, 0.0693]])
02620.jpg is done
tensor([[0.0075, 0.0869, 0.0885, 0.1313, 0.0846, 0.5285, 0.0034, 0.0693]])
02621.jpg is done
tensor([[0.0091, 0.0601, 0.2859, 0.1806, 0.2490, 0.1344, 0.0004, 0.0805]])
02622.jpg is done
tensor([[0.0259, 0.0506, 0.1527, 0.1245, 0.0383, 0.3023, 0.0009, 0.3047]])
02623.jpg is done
tensor([[0.0243, 0.0468, 0.0107, 0.0226, 0.0993, 0.5785, 0.0190, 0.1988]])
02624.jpg is done
tensor([[0.0073, 0.

In [ ]:
print(face_dictionary)
print(len(face_dictionary["a man with no beard"]))
print(len(face_dictionary["a man with a beard"]))
print(len(face_dictionary["a man with a moustache"]))
print(len(face_dictionary["a man without a moustache"]))
print(len(face_dictionary["a person with a round face"]))
print(len(face_dictionary["a person with a slim face"]))
print(len(face_dictionary["a messy looking person"]))
print(len(face_dictionary["a well groomed person"]))

{'a man with a beard': ['00009.jpg', '00009.jpg', '00039.jpg', '00095.jpg', '00099.jpg', '00101.jpg', '00105.jpg', '00112.jpg', '00174.jpg', '00193.jpg', '00196.jpg', '00201.jpg', '00204.jpg', '00218.jpg', '00272.jpg', '00283.jpg', '00295.jpg', '00300.jpg', '00391.jpg', '00491.jpg', '00492.jpg', '00498.jpg', '00503.jpg', '00510.jpg', '00544.jpg', '00614.jpg', '00634.jpg', '00657.jpg', '00725.jpg', '00730.jpg', '00756.jpg', '00818.jpg', '00886.jpg', '00890.jpg', '00927.jpg', '00936.jpg', '00945.jpg', '00960.jpg', '00961.jpg', '00977.jpg', '01026.jpg', '01027.jpg', '01032.jpg', '01034.jpg', '01074.jpg', '01129.jpg', '01144.jpg', '01151.jpg', '01154.jpg', '01165.jpg', '01254.jpg', '01260.jpg', '01280.jpg', '01289.jpg', '01334.jpg', '01349.jpg', '01363.jpg', '01390.jpg', '01397.jpg', '01510.jpg', '01529.jpg', '01587.jpg', '01611.jpg', '01618.jpg', '01619.jpg', '01657.jpg', '01745.jpg', '01756.jpg', '01771.jpg', '01785.jpg', '01816.jpg', '01851.jpg', '01880.jpg', '01883.jpg', '01898.jpg', '